import YangMillsProof.Stage1_GaugeEmbedding.GaugeToLedger
import YangMillsProof.Stage1_GaugeEmbedding.VoxelLattice

-- Re-export
open YangMillsProof.Stage1_GaugeEmbedding.GaugeToLedger
open YangMillsProof.Stage1_GaugeEmbedding.VoxelLattice
