name: Generate Status Badges

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Yang-Mills Proof CI"]
    types:
      - completed

jobs:
  generate-badges:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # Use shields.io endpoint badges instead of gist-based badges
    # These work without requiring gist creation
    
    - name: Generate Build Status
      run: |
        echo "Build Status: ${{ github.event.workflow_run.conclusion }}"
        if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
          echo "BUILD_STATUS=passing" >> $GITHUB_ENV
          echo "BUILD_COLOR=brightgreen" >> $GITHUB_ENV
        else
          echo "BUILD_STATUS=failing" >> $GITHUB_ENV
          echo "BUILD_COLOR=red" >> $GITHUB_ENV
        fi
        
    - name: Run Axiom Check
      run: |
        if ./verify_no_axioms.sh | grep -q "no actual axiom statements found"; then
          echo "AXIOM_STATUS=verified" >> $GITHUB_ENV
          echo "AXIOM_COLOR=blue" >> $GITHUB_ENV
        else
          echo "AXIOM_STATUS=unknown" >> $GITHUB_ENV
          echo "AXIOM_COLOR=orange" >> $GITHUB_ENV
        fi
        
    - name: Run Sorry Check  
      run: |
        if ./verify_no_sorries.sh | grep -q "no actual sorry statements found"; then
          echo "SORRY_STATUS=verified" >> $GITHUB_ENV
          echo "SORRY_COLOR=green" >> $GITHUB_ENV
        else
          echo "SORRY_STATUS=unknown" >> $GITHUB_ENV
          echo "SORRY_COLOR=orange" >> $GITHUB_ENV
        fi
        
    - name: Generate Badge URLs
      run: |
        echo "Badge URLs (for README):"
        echo "Build: ![Build Status](https://img.shields.io/badge/Build-$BUILD_STATUS-$BUILD_COLOR)"
        echo "Axiom-Free: ![Axiom Free](https://img.shields.io/badge/Axiom--Free-$AXIOM_STATUS-$AXIOM_COLOR)"  
        echo "Sorry-Free: ![Sorry Free](https://img.shields.io/badge/Sorry--Free-$SORRY_STATUS-$SORRY_COLOR)" 