name: Yang-Mills Proof CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install elan (Lean version manager)
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
        
    - name: Get Lean dependencies
      run: |
        export PATH="$HOME/.elan/bin:$PATH"
        lake update
      
    - name: Build Yang-Mills proof
      run: |
        export PATH="$HOME/.elan/bin:$PATH"
        echo "🔨 Building Yang-Mills proof..."
        lake build
        echo "✅ Build completed successfully!"
        
    - name: Verify axiom-free status
      run: |
        echo "🔍 Verifying axiom-free status..."
        bash verify_no_axioms.sh
        echo "✅ Axiom verification passed!"
        
    - name: Verify sorry-free status  
      run: |
        echo "🔍 Verifying sorry-free status..."
        bash verify_no_sorries.sh
        echo "✅ Sorry verification passed!"
        
    - name: Generate verification summary
      run: |
        echo "📊 Yang-Mills Proof Verification Summary"
        echo "========================================"
        echo "✅ Build: SUCCESS"
        echo "✅ Axiom-free: VERIFIED"
        echo "✅ Sorry-free: VERIFIED"
        echo ""
        echo "🎯 The proof is complete and formally verified!"
        
    - name: Create build artifacts
      if: success()
      run: |
        echo "BUILD_SUCCESS=true" >> $GITHUB_ENV
        echo "AXIOM_FREE=true" >> $GITHUB_ENV
        echo "SORRY_FREE=true" >> $GITHUB_ENV
        
  verification-status:
    runs-on: ubuntu-latest
    needs: build-and-verify
    if: always()
    
    steps:
    - name: Set verification badges
      run: |
        if [ "${{ needs.build-and-verify.result }}" == "success" ]; then
          echo "🟢 YANG-MILLS PROOF STATUS: VERIFIED"
          echo "✅ Build: SUCCESS"
          echo "✅ Axiom-free: CONFIRMED" 
          echo "✅ Sorry-free: CONFIRMED"
          echo "📜 Formal verification complete!"
        else
          echo "🔴 YANG-MILLS PROOF STATUS: FAILED"
          echo "❌ Verification failed - check logs"
        fi 